<h1>Library Management System</h1>

<p>
    Welcome to the Library Management System.
</p>

<p>
    The Laminas MVC application is working correctly.
</p>

<hr>

<h3>Library Management</h3>

<p>
    Use the buttons below to manage the library.
</p>

<p>
    <a
        href="<?= $this->url('books') ?>"
        class="btn btn-primary"
    >
        Manage Books
    </a>

    <a
        href="<?= $this->url('books-stock') ?>"
        class="btn btn-success"
    >
        Stock & Returned
    </a>
</p>